version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./storage:/app/storage 
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
    command: ["python", "app/main.py"]
