version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - data:/app/storage
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
    command: ["python", "app/main.py"]

volumes:
  data:
    driver: local
